#!/bin/bash

#SBATCH --partition=shared
#SBATCH --job-name=GTFSDownloadJob
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=04:00:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_output_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

# Your job starts in the directory where you call sbatch
cd $HOME/...
# Activate your environment
source activate thesis
# Run your code
srun python -u gtfs_aggregation.py
